version: "2"
services:
  app:
    build: ./Python
    links:
      - db
    ports:
      - "9000:9000"
    volumes:
      - ./Python:/app
  db:
    build: ./mysql
  home:
    build: ./build
    ports:
      - "80:80"
    volumes:
      - ./build:/usr/share/nginx/html
